"""misc changes

Revision ID: 017900da4c8c
Revises: bf04ca9e0652
Create Date: 2021-11-13 09:01:51.284923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017900da4c8c'
down_revision = 'bf04ca9e0652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('service_id', sa.String(length=256), nullable=True))
    op.add_column('artist', sa.Column('service', sa.String(length=32), nullable=True))
    op.add_column('track', sa.Column('service_id', sa.String(length=64), nullable=True))
    op.add_column('track', sa.Column('art', sa.String(length=1024), nullable=True))
    op.add_column('track', sa.Column('href', sa.String(length=1024), nullable=True))
    op.drop_column('track', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('info', sa.VARCHAR(length=2048), nullable=True))
    op.drop_column('track', 'href')
    op.drop_column('track', 'art')
    op.drop_column('track', 'service_id')
    op.drop_column('artist', 'service')
    op.drop_column('artist', 'service_id')
    # ### end Alembic commands ###
