"""blacklist table

Revision ID: 349d11a358dd
Revises: 8c5508170501
Create Date: 2021-11-25 16:53:54.716232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349d11a358dd'
down_revision = '8c5508170501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_column('track_pos')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'playlist', ['playlist_id'], ['id'])

    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_pos', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
