"""removed logged_in column from service table

Revision ID: 35a988d5dcc6
Revises: 7301147ee2fc
Create Date: 2021-10-28 18:43:36.627853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a988d5dcc6'
down_revision = '7301147ee2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'logged_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('logged_in', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
