"""added username column to service table

Revision ID: 7301147ee2fc
Revises: 930f4d828da7
Create Date: 2021-10-28 16:17:50.397821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7301147ee2fc'
down_revision = '930f4d828da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('username', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'username')
    # ### end Alembic commands ###
