"""Added source table

Revision ID: 838131a83eef
Revises: f4b676f07e8c
Create Date: 2021-11-08 13:19:37.937412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838131a83eef'
down_revision = 'f4b676f07e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('service', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('playlist', 'spotify_id')
    op.drop_column('playlist', 'youtube_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('youtube_id', sa.VARCHAR(length=140), nullable=True))
    op.add_column('playlist', sa.Column('spotify_id', sa.VARCHAR(length=140), nullable=True))
    op.drop_table('source')
    # ### end Alembic commands ###
