"""added track_pos column to playlist_track table

Revision ID: 8c5508170501
Revises: eaa6688b6be3
Create Date: 2021-11-23 16:43:58.133193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5508170501'
down_revision = 'eaa6688b6be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_pos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_track', schema=None) as batch_op:
        batch_op.drop_column('track_pos')

    # ### end Alembic commands ###
