"""added a playlist_source association table

Revision ID: b4f03ed55ad3
Revises: 8c5508170501
Create Date: 2021-11-23 17:26:29.037088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f03ed55ad3'
down_revision = '8c5508170501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_source',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('fk_playlist_source_playlist_id_playlist')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_playlist_source_source_id_source'))
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'playlist', ['playlist_id'], ['id'])

    op.drop_table('playlist_source')
    # ### end Alembic commands ###
