"""changed column name in source table

Revision ID: bf04ca9e0652
Revises: 838131a83eef
Create Date: 2021-11-08 13:26:59.556446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf04ca9e0652'
down_revision = '838131a83eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('service_id', sa.String(length=64), nullable=True))
    op.drop_column('source', 'source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('source_id', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('source', 'service_id')
    # ### end Alembic commands ###
