"""added sp andnd yt id columns to Playlist table

Revision ID: f4b676f07e8c
Revises: 80f92fd403c1
Create Date: 2021-11-07 16:03:25.011705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b676f07e8c'
down_revision = '80f92fd403c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('spotify_id', sa.String(length=140), nullable=True))
    op.add_column('playlist', sa.Column('youtube_id', sa.String(length=140), nullable=True))
    op.add_column('playlist', sa.Column('art', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'art')
    op.drop_column('playlist', 'youtube_id')
    op.drop_column('playlist', 'spotify_id')
    # ### end Alembic commands ###
